# Generated by Django 2.2.1 on 2019-07-07 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='competence',
            fields=[
                ('id_competence', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='competence_type',
            fields=[
                ('id_competence_type', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='education',
            fields=[
                ('id_education', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('id_competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.competence')),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id_employee', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id_user', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=500)),
                ('user_image', models.ImageField(default=0, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='workplace',
            fields=[
                ('id_workplace', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('id_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.employee')),
            ],
        ),
        migrations.CreateModel(
            name='participation',
            fields=[
                ('id_participation', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.DateField()),
                ('id_education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.education')),
                ('id_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.employee')),
            ],
        ),
        migrations.CreateModel(
            name='employee_competence',
            fields=[
                ('id_employee_competence', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
                ('level', models.IntegerField(max_length=100)),
                ('id_competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.competence')),
                ('id_employeee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.employee')),
            ],
        ),
        migrations.CreateModel(
            name='competence_relevance',
            fields=[
                ('id_competence_relevance', models.IntegerField(primary_key=True, serialize=False)),
                ('competence_weight', models.IntegerField(max_length=100)),
                ('id_competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.competence')),
                ('id_workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.workplace')),
            ],
        ),
        migrations.AddField(
            model_name='competence',
            name='id_competence_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.competence_type'),
        ),
    ]
