# Generated by Django 2.2.1 on 2019-07-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence_relevance',
            name='competence_weight',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee_competence',
            name='id_employee_competence',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee_competence',
            name='level',
            field=models.IntegerField(),
        ),
    ]
