# Generated by Django 2.2.1 on 2019-08-10 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_hr_user_id_workplace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='for_employee',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='id_education',
        ),
        migrations.AddField(
            model_name='notifications',
            name='desc',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='notifications',
            name='for_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
