# Generated by Django 2.2.1 on 2019-08-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190810_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='image',
            field=models.CharField(default='user_icon.png', max_length=100),
        ),
        migrations.AddField(
            model_name='myuser',
            name='workplaceName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
