# Generated by Django 2.2.1 on 2019-07-08 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190708_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workplace',
            name='id_employee',
        ),
        migrations.AddField(
            model_name='employee',
            name='id_workplace',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.workplace'),
            preserve_default=False,
        ),
    ]
