# Generated by Django 2.2.1 on 2019-07-08 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190708_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id_workplace',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.workplace'),
        ),
    ]
