# Generated by Django 2.2.1 on 2019-07-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190708_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='competence',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
