# Generated by Django 2.2.1 on 2019-07-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_competence_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='desc',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
