# Generated by Django 2.2.1 on 2019-07-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20190710_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='competence',
            name='hoegen_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competence_relevance',
            name='minimum_required',
            field=models.IntegerField(default=0),
        ),
    ]
