# Generated by Django 2.2.1 on 2019-07-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20190710_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
