# Generated by Django 2.2.1 on 2019-07-11 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_user_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='notifications',
            fields=[
                ('id_notification', models.AutoField(primary_key=True, serialize=False)),
                ('seen', models.BooleanField(default=False)),
                ('for_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.user')),
                ('id_education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.education')),
            ],
        ),
    ]
