# Generated by Django 2.2.1 on 2019-07-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workplace',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
