# Generated by Django 2.2.1 on 2019-07-12 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20190711_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='id_competence',
        ),
        migrations.AddField(
            model_name='education',
            name='id_competence',
            field=models.ManyToManyField(to='home.competence'),
        ),
    ]
