# Generated by Django 2.2.1 on 2019-07-12 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20190712_0555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competence_relevance',
            name='minimum_required',
        ),
    ]
