# Generated by Django 2.2.1 on 2019-07-14 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_competence_relevance_minimum_required'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employee_competence',
        ),
    ]
