# Generated by Django 2.2.1 on 2019-07-14 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_delete_employee_competence'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee_competence',
            fields=[
                ('id_employee_competence', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.IntegerField()),
                ('id_competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.competence')),
                ('id_competence_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.competence_type')),
                ('id_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.employee')),
            ],
        ),
    ]
