# Generated by Django 2.2.1 on 2019-08-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20190727_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='hoegen_id',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='competence',
            name='slo_name',
            field=models.CharField(max_length=100),
        ),
    ]
